/**
 * \file	audio.c
 * \brief	Audio core of the hearing aid software.
 *
 * \details	This file contains the I/Os management of the system and by
 *		definition the audio core of the hearing aid.
 */
#include <stdio.h>
#include <stdlib.h>

#include <portaudio.h>
#include "tools.h"
#include "ringbuffer.h"

static PaError err;
static PaStream *stream = {0};

/**
 * \fn		void PaErrorTest(PaError error)
 * \brief	Portaudio error handling
 *
 * \param[in]	error			error generated by Portaudio engine
 *
 * The function will return an error message on stderr if fails
 */
void PaErrorTest(PaError error)
{
	if (error != paNoError) {
		/* using Pa_Terminate is crucial to avoid resource leaks */
		Pa_Terminate();
		fprintf(stderr, "Error: %s\n", Pa_GetErrorText(error));
		exit(EXIT_FAILURE);
	}
}


/**
 * \fn		int PlayrecCallback(const void *input_buffer, void *output_buffer,
 *		unsigned long frames_per_buffer, const PaStreamCallbackTimeInfo *time_info,
 *		PaStreamCallbackFlags status_flags, void *user_data)
 *
 * \brief	Audio callback
 *
 *
 * \param[in] input_buffer		array of interleaved input samples
 * \param[in] output_buffer		array of interleaved output samples
 * \param[in] frames_per_buffer		number of frames to be processed
 * \param[in] time_info			struct with time in seconds
 * \param[in] status_flags		flags indicating whether input and/or
 * \param[in] user_data			pointer to the StreamInfoStruct for this
 *					stream, as passed to Pa_OpenStream()
 *
 * \return	paContinue or paAbort to stop the stream if either user_data
 *		is NULL or stopStream has been set, or paContinue for the
 *		stream to continue running.
 */
int g_num_no_imputs = {0};
int PlayrecCallback(const void *input_buffer,
			   void *output_buffer,
			   unsigned long frames_per_buffer,
			   const PaStreamCallbackTimeInfo *time_info,
			   PaStreamCallbackFlags status_flags,
			   void *user_data)
{
	float *out = (float *) output_buffer;
	const float *in = (const float *)input_buffer;
	unsigned int i;

	(void) time_info;
	(void) status_flags;
	(void) user_data;

	/* we transfer the input samples to the output */
	if (input_buffer != NULL) {
		for (i = 0; i < frames_per_buffer; i++) {
			*out++ = *in++;
			*out++ = *in++;
		}
	}
	return paContinue;
}


/**
 * \fn		static void PaInit(void)
 * \brief	Initialization of Portaudio framework.
 *
 * if an error is raised, the program exit with an error message on stderr.
 */
static void PaInit(void)
{
	static int initialized;

	if (!initialized) {
		err = Pa_Initialize();

		PaErrorTest(err);
		initialized = 1;
	}
}


/**
 * \fn		static void PaClose(PaStream *stream)
 * \brief	Close the audio stream gracefully.
 *
 * \param[in]	stream			Pointer to the audio stream
 *
 * Finish gracefully the audio stream or exit the program if an error is raised
 */
static void PaClose(PaStream *stream)
{
	err = Pa_StopStream(stream);
	PaErrorTest(err);
	Pa_Terminate();
}


/**
 * \fn			void PaOpenStream(void)
 * \brief		Open the audio stream through Portaudio framework.
 *
 * Exit and return an error if raised
 */
void PaOpenStream(void)
{
	PaStreamParameters in_params, out_params;
	int num_channels = 2;
	int samplerate = 44100;
	int device_id = 3;
	int frames_per_buffer = 256;
	char sample_format = paFloat32;

	PaInit();

	/* INPUTS */
	in_params.device = device_id;
	in_params.channelCount = num_channels;
	in_params.sampleFormat = sample_format;
	in_params.suggestedLatency =
		Pa_GetDeviceInfo(in_params.device)->defaultLowInputLatency;
	in_params.hostApiSpecificStreamInfo = NULL;

	/* OUTPUTS */
	out_params.device = device_id;
	out_params.channelCount = num_channels;
	out_params.sampleFormat = sample_format;
	out_params.suggestedLatency =
		Pa_GetDeviceInfo(out_params.device)->defaultLowOutputLatency;
	out_params.hostApiSpecificStreamInfo = NULL;

	RingBuffer_t buffer;

	RingBufferInit(&buffer);

	err = Pa_OpenStream(
			   &stream,
			   &in_params,
			   &out_params,
			   samplerate,
			   frames_per_buffer,
			   paNoFlag, /* portaudio will clip for us */
			   PlayrecCallback,
			   NULL);
	PaErrorTest(err);

	err = Pa_StartStream(stream);
	PaErrorTest(err);

	/* close the program when wanted */
	printf("Hit ENTER to stop program.\n");
	getchar();
	/* stop the stream */
	PaClose(stream);
}
